export const citationSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    name: { type: "string" },
    url: { type: ["string", "null"] },
  },
  required: ["name", "url"],
} as const;

export const scoutSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    notes: { type: "string" },
    sources: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          kind: {
            type: "string",
            enum: [
              "institution",
              "regulator",
              "utility",
              "media",
              "research",
              "financier",
              "company",
              "journalist",
              "database",
              "newsletter",
            ],
          },
          url: { type: ["string", "null"] },
          platform: { type: ["string", "null"] },
          country: { type: ["string", "null"] },
          focus: { type: ["string", "null"] },
          tier: { type: "integer" },
          score_primary: { type: "integer" },
          score_accuracy: { type: "integer" },
          score_expertise: { type: "integer" },
          score_speed: { type: "integer" },
          score_relevance: { type: "integer" },
          score_transparency: { type: "integer" },
          score_independence: { type: "integer" },
          rationale: { type: "string" },
        },
        required: [
          "id",
          "name",
          "kind",
          "url",
          "platform",
          "country",
          "focus",
          "tier",
          "score_primary",
          "score_accuracy",
          "score_expertise",
          "score_speed",
          "score_relevance",
          "score_transparency",
          "score_independence",
          "rationale",
        ],
      },
    },
  },
  required: ["notes", "sources"],
} as const;

const itemSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    event_key: { type: "string" },
    title: { type: "string" },
    what_happened: { type: "string" },
    evidence: { type: "string" },
    what_changed: { type: "string" },
    why_it_matters: { type: "string" },
    who_benefits: { type: "string" },
    who_loses: { type: "string" },
    what_next: { type: "string" },
    netso_meaning: { type: "string" },
    recommended_action: { type: "string" },
    deadline: { type: ["string", "null"] },
    severity: { type: "string", enum: ["critical", "important", "watch"] },
    category: {
      type: "string",
      enum: [
        "policy",
        "regulation",
        "finance",
        "solar",
        "storage",
        "technology",
        "customer",
        "competitor",
        "global",
        "market",
      ],
    },
    impact_tags: { type: "array", items: { type: "string" } },
    confidence: {
      type: "string",
      enum: ["high", "medium", "low", "speculation"],
    },
    verification_level: { type: "integer" },
    conflict_alert: { type: ["string", "null"] },
    impact: { type: "integer" },
    urgency: { type: "integer" },
    probability: { type: "integer" },
    relevance: { type: "integer" },
    quality: { type: "integer" },
    citations: { type: "array", items: citationSchema },
    numbers: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          label: { type: "string" },
          original: { type: "string" },
          converted: { type: ["string", "null"] },
          assumption: { type: ["string", "null"] },
        },
        required: ["label", "original", "converted", "assumption"],
      },
    },
    event_date: { type: ["string", "null"] },
  },
  required: [
    "event_key",
    "title",
    "what_happened",
    "evidence",
    "what_changed",
    "why_it_matters",
    "who_benefits",
    "who_loses",
    "what_next",
    "netso_meaning",
    "recommended_action",
    "deadline",
    "severity",
    "category",
    "impact_tags",
    "confidence",
    "verification_level",
    "conflict_alert",
    "impact",
    "urgency",
    "probability",
    "relevance",
    "quality",
    "citations",
    "numbers",
    "event_date",
  ],
} as const;

export const dailySchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    strategic_interpretation: { type: "string" },
    recommended_actions: { type: "array", items: { type: "string" } },
    items: { type: "array", items: itemSchema },
    assumption_flags: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          assumption_id: { type: "string" },
          new_value: { type: "string" },
          reason: { type: "string" },
        },
        required: ["assumption_id", "new_value", "reason"],
      },
    },
    opportunities: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          id: { type: "string" },
          kind: { type: "string", enum: ["opportunity", "threat"] },
          title: { type: "string" },
          description: { type: "string" },
          potential_value: { type: ["string", "null"] },
          probability: { type: ["string", "null"] },
          time_sensitivity: { type: ["string", "null"] },
          execution_difficulty: { type: ["string", "null"] },
          strategic_fit: { type: ["string", "null"] },
          rank: { type: "integer" },
        },
        required: [
          "id",
          "kind",
          "title",
          "description",
          "potential_value",
          "probability",
          "time_sensitivity",
          "execution_difficulty",
          "strategic_fit",
          "rank",
        ],
      },
    },
  },
  required: [
    "strategic_interpretation",
    "recommended_actions",
    "items",
    "assumption_flags",
    "opportunities",
  ],
} as const;

export const weeklySchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    strategic_interpretation: { type: "string" },
    recommended_actions: { type: "array", items: { type: "string" } },
    biggest: { type: "array", items: { type: "string" } },
    policy: { type: "string" },
    market: { type: "string" },
    competitors: { type: "string" },
    technology: { type: "string" },
    financing: { type: "string" },
    customers: { type: "string" },
    threats: { type: "string" },
    opportunities: { type: "string" },
    numbers: { type: "array", items: { type: "string" } },
    implications: { type: "string" },
    start: { type: "array", items: { type: "string" } },
    stop: { type: "array", items: { type: "string" } },
    defer: { type: "array", items: { type: "string" } },
    accelerate: { type: "array", items: { type: "string" } },
    weekly_actions: { type: "array", items: { type: "string" } },
  },
  required: [
    "strategic_interpretation",
    "recommended_actions",
    "biggest",
    "policy",
    "market",
    "competitors",
    "technology",
    "financing",
    "customers",
    "threats",
    "opportunities",
    "numbers",
    "implications",
    "start",
    "stop",
    "defer",
    "accelerate",
    "weekly_actions",
  ],
} as const;

export const monthlySchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    strategic_interpretation: { type: "string" },
    recommended_actions: { type: "array", items: { type: "string" } },
    market: { type: "string" },
    regulatory: { type: "string" },
    competitor: { type: "string" },
    financing: { type: "string" },
    technology: { type: "string" },
    customer: { type: "string" },
    opportunity: { type: "string" },
    threat: { type: "string" },
    calls: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          initiative: { type: "string" },
          call: {
            type: "string",
            enum: ["scale", "experiment", "shrink", "defer", "kill"],
          },
          why: { type: "string" },
        },
        required: ["initiative", "call", "why"],
      },
    },
  },
  required: [
    "strategic_interpretation",
    "recommended_actions",
    "market",
    "regulatory",
    "competitor",
    "financing",
    "technology",
    "customer",
    "opportunity",
    "threat",
    "calls",
  ],
} as const;
