import type {
  Assumption,
  Brief,
  IntelligenceItem,
  Signal,
  Source,
} from "./types";

export const SEED_SOURCES: Source[] = [
  {
    id: "src-sreda",
    name: "SREDA",
    kind: "regulator",
    url: "http://www.sreda.gov.bd",
    platform: "web",
    country: "Bangladesh",
    focus: "Renewable policy, net metering, rooftop solar standards",
    tier: 1,
    score: 92,
    scorePrimary: 25,
    scoreAccuracy: 18,
    scoreExpertise: 15,
    scoreSpeed: 7,
    scoreRelevance: 15,
    scoreTransparency: 8,
    scoreIndependence: 4,
    rationale: "Primary regulator for rooftop solar, net metering and equipment standards. Directly changes Netso eligibility.",
    lastSignalAt: "2026-09-01",
  },
  {
    id: "src-power-division",
    name: "Power Division, MPEMR",
    kind: "institution",
    url: "https://powerdivision.gov.bd",
    platform: "web",
    country: "Bangladesh",
    focus: "Gazettes, circulars, rooftop incentive design, one-stop service",
    tier: 1,
    score: 95,
    scorePrimary: 25,
    scoreAccuracy: 19,
    scoreExpertise: 14,
    scoreSpeed: 8,
    scoreRelevance: 15,
    scoreTransparency: 9,
    scoreIndependence: 5,
    rationale: "Issued the rooftop solar incentive package. Primary source for policy text.",
    lastSignalAt: "2026-09-01",
  },
  {
    id: "src-berc",
    name: "Bangladesh Energy Regulatory Commission",
    kind: "regulator",
    url: "http://www.berc.org.bd",
    platform: "web",
    country: "Bangladesh",
    focus: "Tariffs, licensing, net metering orders",
    tier: 1,
    score: 90,
    scorePrimary: 25,
    scoreAccuracy: 18,
    scoreExpertise: 14,
    scoreSpeed: 6,
    scoreRelevance: 15,
    scoreTransparency: 8,
    scoreIndependence: 4,
    rationale: "Tariff and licensing authority. Changes industrial electricity economics.",
    lastSignalAt: null,
  },
  {
    id: "src-bpdb",
    name: "Bangladesh Power Development Board",
    kind: "utility",
    url: "https://bpdb.gov.bd",
    platform: "web",
    country: "Bangladesh",
    focus: "Generation, offtake, system data",
    tier: 1,
    score: 84,
    scorePrimary: 22,
    scoreAccuracy: 17,
    scoreExpertise: 13,
    scoreSpeed: 6,
    scoreRelevance: 14,
    scoreTransparency: 8,
    scoreIndependence: 4,
    rationale: "System operator/offtaker context for surplus injection and capacity.",
    lastSignalAt: null,
  },
  {
    id: "src-idcol",
    name: "IDCOL",
    kind: "financier",
    url: "https://idcol.org",
    platform: "web",
    country: "Bangladesh",
    focus: "RE project finance, rooftop solar credit lines",
    tier: 1,
    score: 88,
    scorePrimary: 20,
    scoreAccuracy: 18,
    scoreExpertise: 14,
    scoreSpeed: 7,
    scoreRelevance: 15,
    scoreTransparency: 9,
    scoreIndependence: 5,
    rationale: "Principal domestic RE financier. Changes Netso capital stack.",
    lastSignalAt: null,
  },
  {
    id: "src-bb",
    name: "Bangladesh Bank",
    kind: "institution",
    url: "https://www.bb.org.bd",
    platform: "web",
    country: "Bangladesh",
    focus: "Green refinance, sustainable finance taxonomy",
    tier: 1,
    score: 86,
    scorePrimary: 22,
    scoreAccuracy: 18,
    scoreExpertise: 12,
    scoreSpeed: 6,
    scoreRelevance: 14,
    scoreTransparency: 9,
    scoreIndependence: 5,
    rationale: "Green refinance and bank guidance bind commercial lenders Netso needs.",
    lastSignalAt: null,
  },
  {
    id: "src-bsti",
    name: "Bangladesh Standards and Testing Institution",
    kind: "institution",
    url: "https://bsti.gov.bd",
    platform: "web",
    country: "Bangladesh",
    focus: "Equipment standards for panels, batteries, inverters, meters",
    tier: 1,
    score: 87,
    scorePrimary: 24,
    scoreAccuracy: 17,
    scoreExpertise: 14,
    scoreSpeed: 5,
    scoreRelevance: 15,
    scoreTransparency: 8,
    scoreIndependence: 4,
    rationale: "Incentive package makes BSTI compliance mandatory. SKU gate for Netso.",
    lastSignalAt: "2026-09-01",
  },
  {
    id: "src-dailystar",
    name: "The Daily Star",
    kind: "media",
    url: "https://www.thedailystar.net",
    platform: "web",
    country: "Bangladesh",
    focus: "Business and energy policy reporting",
    tier: 1,
    score: 78,
    scorePrimary: 8,
    scoreAccuracy: 17,
    scoreExpertise: 12,
    scoreSpeed: 9,
    scoreRelevance: 14,
    scoreTransparency: 13,
    scoreIndependence: 5,
    rationale: "High-quality national paper; first detailed write-up of the Tk 10.50 package.",
    lastSignalAt: "2026-09-02",
  },
  {
    id: "src-tbs",
    name: "The Business Standard",
    kind: "media",
    url: "https://www.tbsnews.net",
    platform: "web",
    country: "Bangladesh",
    focus: "Energy, policy, industrial competitiveness",
    tier: 1,
    score: 77,
    scorePrimary: 8,
    scoreAccuracy: 16,
    scoreExpertise: 12,
    scoreSpeed: 9,
    scoreRelevance: 14,
    scoreTransparency: 13,
    scoreIndependence: 5,
    rationale: "Independent confirmation of gazette mechanics and 4,000 MW rooftop ambition.",
    lastSignalAt: "2026-09-01",
  },
  {
    id: "src-reuters",
    name: "Reuters",
    kind: "media",
    url: "https://www.reuters.com",
    platform: "web",
    country: "International",
    focus: "Wire confirmation of Bangladesh energy policy",
    tier: 2,
    score: 74,
    scorePrimary: 6,
    scoreAccuracy: 18,
    scoreExpertise: 10,
    scoreSpeed: 10,
    scoreRelevance: 12,
    scoreTransparency: 13,
    scoreIndependence: 5,
    rationale: "International confirmation; useful for investors, not a substitute for the gazette.",
    lastSignalAt: "2026-09-02",
  },
  {
    id: "src-ieefa",
    name: "IEEFA",
    kind: "research",
    url: "https://ieefa.org",
    platform: "web",
    country: "International",
    focus: "Bangladesh RE transition, fuel-import savings, rooftop economics",
    tier: 2,
    score: 72,
    scorePrimary: 10,
    scoreAccuracy: 16,
    scoreExpertise: 14,
    scoreSpeed: 5,
    scoreRelevance: 13,
    scoreTransparency: 10,
    scoreIndependence: 4,
    rationale: "Serious energy-finance research on Bangladesh rooftop solar barriers.",
    lastSignalAt: "2026-02-03",
  },
  {
    id: "src-ifc",
    name: "IFC / World Bank",
    kind: "financier",
    url: "https://www.ifc.org",
    platform: "web",
    country: "International",
    focus: "Climate finance, C&I solar, emerging-market distributed energy",
    tier: 2,
    score: 80,
    scorePrimary: 15,
    scoreAccuracy: 17,
    scoreExpertise: 14,
    scoreSpeed: 5,
    scoreRelevance: 13,
    scoreTransparency: 11,
    scoreIndependence: 5,
    rationale: "Potential DFI capital and market diagnostics for C&I solar.",
    lastSignalAt: null,
  },
  {
    id: "src-iea",
    name: "International Energy Agency",
    kind: "research",
    url: "https://www.iea.org",
    platform: "web",
    country: "International",
    focus: "Solar PV costs, storage, distributed energy, energy reviews",
    tier: 2,
    score: 81,
    scorePrimary: 18,
    scoreAccuracy: 18,
    scoreExpertise: 15,
    scoreSpeed: 5,
    scoreRelevance: 10,
    scoreTransparency: 11,
    scoreIndependence: 4,
    rationale: "Primary global energy statistics; use for CAPEX and storage cost trends.",
    lastSignalAt: null,
  },
  {
    id: "src-irena",
    name: "IRENA",
    kind: "research",
    url: "https://www.irena.org",
    platform: "web",
    country: "International",
    focus: "RE costs, distributed generation, policy catalogues",
    tier: 2,
    score: 79,
    scorePrimary: 18,
    scoreAccuracy: 17,
    scoreExpertise: 14,
    scoreSpeed: 5,
    scoreRelevance: 10,
    scoreTransparency: 11,
    scoreIndependence: 4,
    rationale: "Authoritative RE cost and policy dataset.",
    lastSignalAt: null,
  },
  {
    id: "src-adb",
    name: "Asian Development Bank",
    kind: "financier",
    url: "https://www.adb.org",
    platform: "web",
    country: "International",
    focus: "Bangladesh power sector, climate finance",
    tier: 2,
    score: 76,
    scorePrimary: 15,
    scoreAccuracy: 16,
    scoreExpertise: 13,
    scoreSpeed: 5,
    scoreRelevance: 12,
    scoreTransparency: 10,
    scoreIndependence: 5,
    rationale: "Active in Bangladesh power; possible blended-finance counterpart.",
    lastSignalAt: null,
  },
  {
    id: "src-nbr",
    name: "National Board of Revenue",
    kind: "institution",
    url: "https://nbr.gov.bd",
    platform: "web",
    country: "Bangladesh",
    focus: "Customs, VAT, SROs on solar equipment",
    tier: 1,
    score: 83,
    scorePrimary: 23,
    scoreAccuracy: 17,
    scoreExpertise: 10,
    scoreSpeed: 6,
    scoreRelevance: 14,
    scoreTransparency: 8,
    scoreIndependence: 5,
    rationale: "Tax and duty changes move Netso CAPEX immediately.",
    lastSignalAt: null,
  },
  {
    id: "src-fe",
    name: "The Financial Express",
    kind: "media",
    url: "https://thefinancialexpress.com.bd",
    platform: "web",
    country: "Bangladesh",
    focus: "Banking, energy, industrial policy",
    tier: 2,
    score: 68,
    scorePrimary: 6,
    scoreAccuracy: 15,
    scoreExpertise: 11,
    scoreSpeed: 8,
    scoreRelevance: 13,
    scoreTransparency: 11,
    scoreIndependence: 4,
    rationale: "Reliable business daily for financing and industrial electricity.",
    lastSignalAt: null,
  },
  {
    id: "src-textile-today",
    name: "Textile Today",
    kind: "media",
    url: "https://textiletoday.com.bd",
    platform: "web",
    country: "Bangladesh",
    focus: "RMG energy costs, green factory, buyer ESG",
    tier: 2,
    score: 70,
    scorePrimary: 8,
    scoreAccuracy: 14,
    scoreExpertise: 13,
    scoreSpeed: 7,
    scoreRelevance: 15,
    scoreTransparency: 9,
    scoreIndependence: 4,
    rationale: "Customer-market primary for RMG energy pain and buyer requirements.",
    lastSignalAt: null,
  },
  {
    id: "src-solar-sreda",
    name: "SREDA Solar Portal",
    kind: "database",
    url: "https://solar.sreda.gov.bd",
    platform: "web",
    country: "Bangladesh",
    focus: "Net-metered rooftop statistics, certified equipment",
    tier: 1,
    score: 89,
    scorePrimary: 25,
    scoreAccuracy: 17,
    scoreExpertise: 14,
    scoreSpeed: 6,
    scoreRelevance: 15,
    scoreTransparency: 8,
    scoreIndependence: 4,
    rationale: "Primary installed-capacity and certification database.",
    lastSignalAt: null,
  },
  {
    id: "src-ember",
    name: "Ember",
    kind: "research",
    url: "https://ember-energy.org",
    platform: "web",
    country: "International",
    focus: "Electricity data, solar deployment, emerging Asia",
    tier: 3,
    score: 64,
    scorePrimary: 12,
    scoreAccuracy: 15,
    scoreExpertise: 12,
    scoreSpeed: 6,
    scoreRelevance: 8,
    scoreTransparency: 8,
    scoreIndependence: 3,
    rationale: "Useful global electricity dataset; lower Bangladesh specificity.",
    lastSignalAt: null,
  },
];

function pri(impact: number, urgency: number, probability: number, relevance: number, quality: number) {
  return Math.round((impact * urgency * probability * relevance * quality) / 1000);
}

export const SEED_ITEMS: IntelligenceItem[] = [
  {
    id: "evt-bd-rts-incentive-2026",
    eventKey: "bd-rooftop-solar-battery-incentive-2026",
    title: "Battery-backed rooftop solar incentive set at Tk 10.50/kWh",
    whatHappened:
      "The Ministry of Power, Energy and Mineral Resources announced a special incentive for rooftop solar systems with battery storage. Eligible surplus electricity supplied to the national grid is priced at Tk 10.50 per unit. Multiple national and wire outlets reported a government circular/gazette around 1–2 September 2026. The package is described as operating under the Net Metering Guidelines 2025.",
    evidence:
      "The Daily Star (2 Sep 2026), The Business Standard (1–2 Sep 2026) and Reuters (2 Sep 2026) independently report the Tk 10.50 figure, battery requirement, 28 Feb 2027 installation cutoff, three-year payment window to 28 Feb 2030, BSTI/SREDA equipment standards, and bank/MFS-only settlement. Power Division circular cited by TBS: max generation cost Tk 8/unit + 20% profit + 11.25% premium = Tk 10.50. Gazette PDF has not been ingested by NEIA — treat beneficiary-of-record and RESCO eligibility as unverified.",
    whatChanged:
      "Bangladesh moved from a net-metering / avoided-cost logic toward a time-limited, battery-mandatory, cash-settled surplus tariff above the stated average retail grid price (Tk 10.40/unit per Daily Star). Battery storage is no longer optional for this incentive. There is now a hard origination/installation clock.",
    whyItMatters:
      "This is the largest rooftop-solar commercial rule change in Bangladesh this year. It can reprice surplus kWh, force battery into the default C&I design, and compress Netso's sales-to-COD cycle into the period before 28 February 2027.",
    whoBenefits:
      "Owners of battery-backed rooftop systems installed by the cutoff who can export surplus and receive DISCOM-administered payments; compliant equipment suppliers; developers who can close interconnection fast.",
    whoLoses:
      "Solar-only (no battery) designs chasing this tariff; slow-moving developers; any PPA/RESCO structure that is later found ineligible as 'customer-installed'.",
    whatNext:
      "Expect implementation circulars from distribution utilities, queueing at one-stop service centres, and a fight over whether third-party-owned systems qualify. Equipment certification lists will become a bottleneck.",
    netsoMeaning:
      "Netso's unit-economic model, product mix and PPA contracts must be re-tested against a battery-mandatory, 3-year kicker — not a 20-year tariff. The window is real; the legal beneficiary is not yet proven from primary text.",
    recommendedAction:
      "Obtain the gazette PDF today. Counsel to confirm whether RESCO/PPA/BOO systems qualify, or only customer-owned. Re-run battery-backed vs solar-only IRRs with Tk 10.50 as a scenario, not the base case. Freeze BSTI/SREDA-compliant SKUs.",
    deadline: "2026-09-10 gazette/eligibility; 2027-02-28 installation cutoff",
    severity: "critical",
    category: "policy",
    impactTags: ["revenue", "margin", "capex", "regulation", "demand", "financing", "strategy"],
    confidence: "high",
    verificationLevel: 4,
    conflictAlert:
      "EFFECTIVE DATE CONFLICT. Reuters and several local recaps: 1 September 2026. Daily Star: scheme effective 2 September 2026. TBS: gazette issued 1 September 2026 and 'came into effect yesterday' (wording that points at 30–31 August depending on TBS's clock). Tariff (Tk 10.50), cutoff (28 Feb 2027) and battery requirement agree across outlets. Likely explanation: gazette publication vs. force-date vs. press date. Check next: the gazette's 'come into force' clause. Do not use a single effective date in customer contracts until the PDF is read.",
    impact: 9,
    urgency: 10,
    probability: 9,
    relevance: 10,
    quality: 8,
    priorityScore: pri(9, 10, 9, 10, 8),
    citations: [
      { name: "The Daily Star", url: "https://www.thedailystar.net/business/economy/news/rooftop-solar-gets-new-incentive-package-4262426" },
      { name: "The Business Standard", url: "https://www.tbsnews.net/bangladesh/energy/solar-producers-get-tk1050-unit-under-new-rooftop-incentive-scheme-1530446" },
      { name: "Reuters", url: "https://www.reuters.com/business/energy/bangladesh-offers-rooftop-solar-incentives-ease-power-shortages-2026-09-02/" },
    ],
    numbers: [
      { label: "Surplus tariff", original: "Tk 10.50 / kWh", converted: "≈ USD 0.086 / kWh", assumption: "Reuters USD conversion as published 2 Sep 2026" },
      { label: "Stated generation-cost cap", original: "Tk 8.00 / kWh", converted: null, assumption: null },
      { label: "Profit margin in tariff build-up", original: "20%", converted: null, assumption: null },
      { label: "Premium in tariff build-up", original: "11.25%", converted: null, assumption: null },
      { label: "Average retail grid price (reported)", original: "Tk 10.40 / kWh", converted: null, assumption: "Daily Star, 2 Sep 2026" },
    ],
    eventDate: "2026-09-01",
    createdAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "evt-eligibility-resco-gap",
    eventKey: "bd-rts-incentive-beneficiary-of-record",
    title: "Beneficiary of record for Tk 10.50 is not confirmed for RESCO/PPA",
    whatHappened:
      "All major recaps describe 'customers' or 'consumers' who install rooftop systems by 28 February 2027 and export surplus after self-consumption. None of the secondary sources quote a clause that clearly includes or excludes third-party ownership, PPA, BOO or RESCO structures.",
    evidence:
      "Daily Star, TBS and Reuters language is consumer/customer-centric. Gazette text not in NEIA. Treat as LEVEL 2–3 on the reporting, LEVEL 1 on the legal conclusion. UNVERIFIED — DO NOT USE FOR CONTRACT DRAFTING.",
    whatChanged:
      "A high-value tariff now exists whose capture by a zero-CAPEX developer is legally ambiguous.",
    whyItMatters:
      "If only the on-site customer is the beneficiary, Netso's PPA product either cannot monetise the kicker, must pass it through, or must be re-papered so the customer is owner of record. That is a product-architecture issue, not a marketing issue.",
    whoBenefits:
      "Customer-owned / capex-outlay buyers, if the gazette is consumer-centric.",
    whoLoses:
      "Unadapted RESCO/PPA originators if third-party systems are ineligible.",
    whatNext:
      "Power Division FAQ, DISCOM implementation guideline, or a law-firm read of the gazette will resolve this. Until then, two product tracks.",
    netsoMeaning:
      "Do not sell 'we will get you Tk 10.50' under a PPA until counsel signs off. Prepare an owner-of-record variant and a pass-through variant.",
    recommendedAction:
      "Legal memo in 5 days: (a) who is paid, (b) can rights be assigned, (c) does Netso-as-operator still qualify if the customer is the net-metering account holder.",
    deadline: "2026-09-08",
    severity: "critical",
    category: "regulation",
    impactTags: ["revenue", "regulation", "financing", "strategy", "risk"],
    confidence: "medium",
    verificationLevel: 2,
    conflictAlert: null,
    impact: 9,
    urgency: 9,
    probability: 7,
    relevance: 10,
    quality: 6,
    priorityScore: pri(9, 9, 7, 10, 6),
    citations: [
      { name: "The Daily Star", url: "https://www.thedailystar.net/business/economy/news/rooftop-solar-gets-new-incentive-package-4262426" },
      { name: "The Business Standard", url: "https://www.tbsnews.net/bangladesh/energy/solar-producers-get-tk1050-unit-under-new-rooftop-incentive-scheme-1530446" },
    ],
    numbers: [],
    eventDate: "2026-09-02",
    createdAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "evt-4000mw-target",
    eventKey: "bd-4000mw-rooftop-ambition-2026",
    title: "Power Division ambition: up to 4,000 MW rooftop solar within a year",
    whatHappened:
      "TBS, citing Power Division materials tied to an 19 August meeting, reports a scheme aim of adding up to 4,000 MW of rooftop solar capacity within one year, inside a broader 5,500 MW / 20% renewable-electricity plan by 2030.",
    evidence:
      "The Business Standard, 1–2 September 2026, referencing Power Division meeting minutes of 19 August. Not independently confirmed in the Daily Star recap. Treat the 4,000 MW figure as LEVEL 2 until a public target document is filed.",
    whatChanged:
      "Political appetite for rooftop scale is being stated in gigawatt language, not rooftop-pilot language.",
    whyItMatters:
      "A 4,000 MW year would overwhelm interconnection, certified equipment and skilled EPC. First movers with standardised designs capture disproportionate origination.",
    whoBenefits: "Prepared C&I platforms, certified suppliers, DISCOMs that staff one-stop centres.",
    whoLoses: "Bespoke, slow, uncertified EPC shops.",
    whatNext: "Watch whether 4,000 MW appears in a formal SREDA/Power Division target or remains meeting-minute language.",
    netsoMeaning:
      "Origination capacity, not panel price, is the binding constraint if even a fraction of 4,000 MW is real. Netso should industrialise a battery-backed C&I block, not custom-engineer every roof.",
    recommendedAction:
      "Set a 90-day origination machine: standard 200–500 kWp + BESS block, DISCOM one-stop playbook, RMG/industrial park list.",
    deadline: "2026-09-30",
    severity: "important",
    category: "policy",
    impactTags: ["demand", "strategy", "competition", "fundraising"],
    confidence: "medium",
    verificationLevel: 2,
    conflictAlert: "4,000 MW / 1-year figure is reported by TBS from Power Division minutes, not yet seen in Daily Star or Reuters. Do not treat as gazetted target.",
    impact: 8,
    urgency: 7,
    probability: 6,
    relevance: 9,
    quality: 6,
    priorityScore: pri(8, 7, 6, 9, 6),
    citations: [
      { name: "The Business Standard", url: "https://www.tbsnews.net/bangladesh/energy/solar-producers-get-tk1050-unit-under-new-rooftop-incentive-scheme-1530446" },
    ],
    numbers: [
      { label: "Reported rooftop ambition", original: "4,000 MW in one year", converted: null, assumption: "TBS citing Power Division; unverified as formal target" },
      { label: "2030 RE plan (reported)", original: "5,500 MW / 20% of electricity", converted: null, assumption: "TBS citing 19 Aug Power Division meeting" },
    ],
    eventDate: "2026-08-19",
    createdAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "evt-bsti-sreda-mandate",
    eventKey: "bd-rts-bsti-sreda-equipment-mandate",
    title: "BSTI + SREDA standards are now a commercial gate, not a quality nice-to-have",
    whatHappened:
      "The incentive recaps make BSTI and SREDA technical standards mandatory for panels, batteries, inverters and meters. Non-compliant kits are ineligible.",
    evidence:
      "Daily Star, TBS, Reuters — consistent. Primary standards lists live on SREDA/BSTI sites; NEIA has not yet diffed the current certified SKU list against typical C&I bills of materials.",
    whatChanged:
      "Equipment selection is now an eligibility risk, not only a performance/warranty choice.",
    whyItMatters:
      "A cheaper uncertified battery that saves CAPEX can destroy the Tk 10.50 kicker and possibly interconnection.",
    whoBenefits: "Bankable, certified manufacturers already on SREDA lists.",
    whoLoses: "Grey-market modules and uncertified BESS packs.",
    whatNext: "Certification queues; possible shortages of listed LFP commercial batteries.",
    netsoMeaning:
      "SKU standardisation is now a financing and incentive-eligibility decision. Procurement must lock listed products.",
    recommendedAction:
      "Publish an internal certified BOM this week. Ban non-listed batteries from any incentive-track proposal.",
    deadline: "2026-09-12",
    severity: "important",
    category: "technology",
    impactTags: ["capex", "technology", "regulation", "risk"],
    confidence: "high",
    verificationLevel: 3,
    conflictAlert: null,
    impact: 7,
    urgency: 8,
    probability: 9,
    relevance: 9,
    quality: 7,
    priorityScore: pri(7, 8, 9, 9, 7),
    citations: [
      { name: "The Daily Star", url: "https://www.thedailystar.net/business/economy/news/rooftop-solar-gets-new-incentive-package-4262426" },
      { name: "The Business Standard", url: "https://www.tbsnews.net/bangladesh/energy/solar-producers-get-tk1050-unit-under-new-rooftop-incentive-scheme-1530446" },
    ],
    numbers: [],
    eventDate: "2026-09-01",
    createdAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "evt-three-year-kicker",
    eventKey: "bd-rts-incentive-tenor-3y",
    title: "The kicker is three years, not a 20-year PPA substitute",
    whatHappened:
      "Payments for surplus at Tk 10.50 are described as running until 28 February 2030 — a three-year window for systems installed by 28 February 2027. Cash is forbidden; settlement is bank or MFS, administered with DISCOM metering records.",
    evidence:
      "Consistent across Daily Star, TBS, Reuters. Primary gazette not in hand for the exact start of the three-year clock (commissioning date vs. gazette date).",
    whatChanged:
      "A time-bounded export credit appeared. It does not, on reported facts, replace long-term offtake or net-metering for the rest of system life.",
    whyItMatters:
      "Lenders will not underwrite 15-year DSCR on a 3-year incentive. Using Tk 10.50 as the life-of-project tariff in a customer proposal is a misselling risk.",
    whoBenefits: "Projects that COD early in the window and can monetise years 1–3 as upside.",
    whoLoses: "Sales narratives that treat 10.50 as perpetual.",
    whatNext: "Banks will haircut the kicker; sophisticated customers will ask what happens on 1 March 2030.",
    netsoMeaning:
      "Model three layers: (1) behind-the-meter avoided tariff, (2) residual net-metering/export after 2030, (3) 2027–2030 kicker as upside. Never collapse them.",
    recommendedAction:
      "Update the assumption ledger and every live proposal template: kicker = scenario, base case = avoided retail + post-2030 rules.",
    deadline: "2026-09-07",
    severity: "important",
    category: "finance",
    impactTags: ["financing", "margin", "fundraising", "risk"],
    confidence: "high",
    verificationLevel: 3,
    conflictAlert: null,
    impact: 8,
    urgency: 8,
    probability: 8,
    relevance: 10,
    quality: 7,
    priorityScore: pri(8, 8, 8, 10, 7),
    citations: [
      { name: "Reuters", url: "https://www.reuters.com/business/energy/bangladesh-offers-rooftop-solar-incentives-ease-power-shortages-2026-09-02/" },
      { name: "The Daily Star", url: "https://www.thedailystar.net/business/economy/news/rooftop-solar-gets-new-incentive-package-4262426" },
    ],
    numbers: [
      { label: "Incentive tenor (reported)", original: "until 28 February 2030", converted: "3 years from the installation cutoff", assumption: "Clock alignment with COD is unverified" },
    ],
    eventDate: "2026-09-01",
    createdAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "evt-grid-price-parity",
    eventKey: "bd-retail-tariff-vs-incentive-10-40",
    title: "Reported retail grid price Tk 10.40 vs incentive Tk 10.50",
    whatHappened:
      "Daily Star states the average retail price of grid electricity is Tk 10.40 per unit, 10 poisha below the new surplus incentive.",
    evidence:
      "Single-outlet figure (Daily Star, 2 Sep 2026). Industrial tariffs vary by voltage, time-of-use and demand charge — 'average retail' is not a C&I bill. LEVEL 2. Do not use 10.40 as Netso's customer tariff without BERC schedule and the actual bill.",
    whatChanged:
      "On the reported averages, exporting surplus is roughly at retail parity, not a deep discount to grid.",
    whyItMatters:
      "For C&I, value is still dominated by behind-the-meter displacement, demand charges, diesel/backup and reliability — not a 10-poisha export spread.",
    whoBenefits: "Honest origination (reliability + avoided energy).",
    whoLoses: "Pitch decks that lead with 'sell to grid at a premium' without bill analysis.",
    whatNext: "Pull BERC C&I schedules and 5 sample RMG bills.",
    netsoMeaning:
      "Keep the primary sales argument on reliability and behind-the-meter savings. Treat export credit as a sweetener.",
    recommendedAction:
      "Replace any generic 'Tk/kWh savings' slide with bill-true C&I tariffs; store them on the ledger.",
    deadline: "2026-09-15",
    severity: "important",
    category: "market",
    impactTags: ["demand", "margin", "strategy"],
    confidence: "medium",
    verificationLevel: 2,
    conflictAlert: null,
    impact: 6,
    urgency: 6,
    probability: 7,
    relevance: 9,
    quality: 6,
    priorityScore: pri(6, 6, 7, 9, 6),
    citations: [
      { name: "The Daily Star", url: "https://www.thedailystar.net/business/economy/news/rooftop-solar-gets-new-incentive-package-4262426" },
    ],
    numbers: [
      { label: "Reported average retail grid", original: "Tk 10.40 / kWh", converted: null, assumption: "Daily Star average; not a C&I tariff schedule" },
      { label: "Incentive surplus tariff", original: "Tk 10.50 / kWh", converted: null, assumption: null },
    ],
    eventDate: "2026-09-02",
    createdAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "evt-disco-payment-ops",
    eventKey: "bd-rts-disco-payment-administration",
    title: "DISCOMs will meter, record and pay — implementation is the silent risk",
    whatHappened:
      "Recaps assign power distribution companies to maintain customer information, measure import/export, and route incentive payments to bank or MFS accounts. Power Division one-stop service centres and district/upazila utility offices are named as support.",
    evidence:
      "Daily Star and TBS. No SLA, settlement lag, or dispute process published in those recaps.",
    whatChanged:
      "Cash-flow of the kicker sits with utility administration, not a bilateral PPA with a corporate offtaker.",
    whyItMatters:
      "Bangladesh DISCOM payment culture is a known project-finance risk. A 3-year incentive that pays 90 days late has a different NPV.",
    whoBenefits: "Projects in DISCOMs with working net-metering ops.",
    whoLoses: "Projects that underwrite month-1 cash.",
    whatNext: "Watch first settlement circulars from DPDC, DESCO, WZPDCL, BREB, C-area utilities.",
    netsoMeaning:
      "Haircut incentive cash-flow in the model. Map which DISCOMs Netso will actually file in first.",
    recommendedAction:
      "Build a DISCOM scorecard (net-metering cycle time, payment lag) before picking the first 20 roofs.",
    deadline: "2026-09-20",
    severity: "watch",
    category: "finance",
    impactTags: ["financing", "risk", "regulation"],
    confidence: "medium",
    verificationLevel: 2,
    conflictAlert: null,
    impact: 7,
    urgency: 5,
    probability: 7,
    relevance: 8,
    quality: 5,
    priorityScore: pri(7, 5, 7, 8, 5),
    citations: [
      { name: "The Daily Star", url: "https://www.thedailystar.net/business/economy/news/rooftop-solar-gets-new-incentive-package-4262426" },
    ],
    numbers: [],
    eventDate: "2026-09-02",
    createdAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "evt-ieefa-barriers",
    eventKey: "ieefa-bd-rooftop-barriers-2026-02",
    title: "IEEFA still flags duty on accessories and slow rooftop credit as binding constraints",
    whatHappened:
      "IEEFA's February 2026 note argued Bangladesh could save ~Tk 22.4 million per year in fuel imports per 1 MW of rooftop solar (their assumptions), and recommended a time-limited duty waiver on rooftop accessories plus a Bangladesh Bank dedicated rooftop fund with single-stage approval.",
    evidence:
      "IEEFA, 3 February 2026. Primary research. This week's incentive does not, in the press recaps, waive duties or create a dedicated BB window. Those recommendations remain open.",
    whatChanged:
      "Policy moved on surplus tariff and batteries; not obviously on customs or refinance plumbing.",
    whyItMatters:
      "CAPEX and debt delay can erase a 3-year kicker. Netso still needs cheaper kit and faster debt.",
    whoBenefits: "If duty waiver appears: importers of BOS/accessories.",
    whoLoses: "Status quo if only the tariff moves and CAPEX stays sticky.",
    whatNext: "Watch NBR SROs and Bangladesh Bank sustainable-finance circulars.",
    netsoMeaning:
      "Do not assume the incentive solved bankability. Parallel workstream on green refinance and duties.",
    recommendedAction:
      "Keep an NBR/BB watch. Do not stop IDCOL/commercial-bank conversations because a surplus tariff exists.",
    deadline: null,
    severity: "watch",
    category: "finance",
    impactTags: ["capex", "financing"],
    confidence: "medium",
    verificationLevel: 4,
    conflictAlert: null,
    impact: 6,
    urgency: 4,
    probability: 6,
    relevance: 8,
    quality: 8,
    priorityScore: pri(6, 4, 6, 8, 8),
    citations: [
      { name: "IEEFA", url: "https://ieefa.org/resources/getting-bangladeshs-renewable-energy-transition-track" },
    ],
    numbers: [
      { label: "IEEFA fuel-import saving per 1 MW rooftop", original: "≈ Tk 22.4 million / year", converted: "≈ USD 0.18 million / year", assumption: "IEEFA: furnace oil Tk 16/kWh, 4 hours/day, 350 days; excludes capacity charges" },
    ],
    eventDate: "2026-02-03",
    createdAt: "2026-09-03T00:00:00.000Z",
  },
];

export const SEED_BRIEF_DAILY: Brief = {
  id: "brief-daily-2026-09-03",
  kind: "daily",
  briefDate: "2026-09-03",
  strategicInterpretation:
    "The information environment around Netso shifted this week from 'rooftop solar is policy-supported' to 'battery-backed rooftop has a dated commercial window.' The Tk 10.50 surplus tariff, the 28 February 2027 installation cutoff, and mandatory BSTI/SREDA kit are the three facts that survive cross-source checks. What did not survive: a single effective date, a gazetted 4,000 MW target, and any proof that a RESCO/PPA vehicle is the payee. The correct founder posture is not celebration. It is a 72-hour legal read, a model review, and an origination sprint that still works if the kicker is treated as a 3-year upside rather than a new business model.",
  recommendedActions: [
    "Get the gazette PDF and a written opinion on beneficiary-of-record (customer vs RESCO/PPA) by 8 September.",
    "Re-cut unit economics: battery-backed vs solar-only; kicker as scenario; base case = behind-the-meter + post-2030 rules.",
    "Lock a BSTI/SREDA-compliant module / hybrid inverter / LFP SKU list; remove uncertified batteries from incentive-track offers.",
    "Stand up a 28 February 2027 COD clock on every live roof, with interconnection slack.",
    "Do not rewrite long-term PPA prices solely off a three-year credit administered by DISCOMs.",
  ],
  startStop: {},
  maps: {},
};

export const SEED_BRIEF_WEEKLY: Brief = {
  id: "brief-weekly-2026-09-01",
  kind: "weekly",
  briefDate: "2026-09-01",
  strategicInterpretation:
    "Week of 1 September 2026: the external rulebook for Bangladeshi rooftop solar changed more than it had in the prior year. Battery is now on the critical path for the headline incentive. Time is now a product feature.",
  recommendedActions: [
    "Legal: gazette + RESCO eligibility.",
    "Finance: three-layer model (BTM, kicker, residual).",
    "Procurement: certified BOM.",
    "Sales: stop leading with grid-export premium.",
    "Ops: DISCOM one-stop map for first 20 sites.",
  ],
  startStop: {
    biggest: [
      "Battery-backed rooftop incentive at Tk 10.50/kWh for eligible surplus.",
      "Installation cutoff 28 February 2027; payments described through 28 February 2030.",
      "Equipment standards (BSTI/SREDA) made mandatory for the scheme.",
    ],
    policy:
      "Special incentive via Power Division circular/gazette, described as sitting on Net Metering Guidelines 2025. Effective-date wording conflicts across outlets. 4,000 MW rooftop-in-a-year language is meeting-minute grade, not confirmed gazetted target.",
    market:
      "Reported average retail grid Tk 10.40 vs incentive Tk 10.50 — export is not a juicy spread. C&I value remains BTM energy, demand charges, diesel and uptime.",
    competitors:
      "No evidenced competitor product launch this week. The race is implicit: anyone who can deliver certified battery-backed C&I before the cutoff.",
    technology:
      "Hybrid inverters, listed LFP, and compliant meters become eligibility hardware. Solar-only designs are off this particular tariff.",
    financing:
      "Three-year DISCOM-administered credit will be haircut by lenders. IDCOL / Bangladesh Bank refinance still required. IEEFA's duty-waiver and dedicated-fund recommendations are unaddressed in the press recaps of this package.",
    customers:
      "C&I and household consumers are the named beneficiaries in recaps. RMG/export factories remain the strategic offtake for Netso but must be sold on bills and reliability, with the kicker as a structured maybe.",
    threats:
      "Legal mismatch with PPA ownership; DISCOM payment lag; certified-BESS shortage; sales teams over-claiming a perpetual 10.50 tariff; compressed COD creating quality/safety risk on batteries.",
    opportunities:
      "Origination sprint; standardised 200–500 kWp + BESS block; owner-of-record contract variant; investor story ('policy window') if eligibility is clean.",
    numbers: [
      "Tk 10.50 / kWh surplus (reported)",
      "Tk 8.00 / kWh stated cost cap + 20% + 11.25%",
      "Tk 10.40 / kWh reported average retail",
      "28 Feb 2027 install cutoff",
      "28 Feb 2030 kicker end",
      "4,000 MW rooftop ambition (TBS / Power Division minutes — unverified as target)",
    ],
    implications:
      "Netso should operate as if a dated battery-backed window is real, and as if the PPA product might not automatically capture it.",
    start: [
      "Gazette capture and counsel memo on beneficiary-of-record.",
      "Certified battery-backed C&I BOM.",
      "COD-by-Feb-2027 pipeline flag in CRM.",
    ],
    stop: [
      "Selling solar-only systems into the incentive narrative.",
      "Using Tk 10.50 as a 15–20 year PPA price.",
      "Uncertified battery options on incentive-track quotes.",
    ],
    defer: [
      "Repositioning the whole company around grid-export.",
      "Waiting for a dedicated Bangladesh Bank rooftop fund before originating.",
    ],
    accelerate: [
      "RMG/industrial origination with battery-backed designs.",
      "DISCOM one-stop relationships.",
      "Model review of every live proposal.",
    ],
    weeklyActions: [
      "Gazette + legal memo.",
      "Ledger update and proposal-template rewrite.",
      "Certified SKU lock.",
      "Top-30 roof list with interconnection estimate.",
      "Investor note: window, not a new perpetual tariff.",
    ],
  },
  maps: {},
};

export const SEED_BRIEF_MONTHLY: Brief = {
  id: "brief-monthly-2026-09",
  kind: "monthly",
  briefDate: "2026-09-01",
  strategicInterpretation:
    "If I were Netso's CEO: the external environment now prices time and batteries. Strategy should not pivot to 'we are a grid-export company.' It should pivot to 'we can deliver certified battery-backed C&I before a known date, without betting the balance sheet on a three-year DISCOM credit.'",
  recommendedActions: [
    "SCALE certified battery-backed C&I origination against the February 2027 clock.",
    "EXPERIMENT with an owner-of-record contract so customers, not Netso, are the payee if that is what the gazette requires.",
    "DEFER any plan that needs the kicker to clear DSCR.",
  ],
  startStop: {},
  maps: {
    market:
      "C&I rooftop demand is still driven by tariffs, diesel and uptime. The new surplus price sits near reported retail average, so export is not the product. Reliability and BTM remain the purchase argument.",
    regulatory:
      "A dated, battery-mandatory incentive is the new rule. Gazette text, RESCO eligibility and DISCOM settlement are the open regulatory risks. Net Metering Guidelines 2025 are the legal wrapper according to recaps.",
    competitor:
      "No evidenced new platform launch this week. Competitive threat is speed-to-COD on certified BESS, not a pricing war yet.",
    financing:
      "Green refinance, IDCOL and DFI capital still matter more than the kicker. Lenders will treat Tk 10.50 as short-dated upside.",
    technology:
      "Hybrid inverter + listed LFP + compliant meter is the default stack for incentive-track. Solar-only remains valid only for customers who do not need the kicker.",
    customer:
      "RMG and export manufacturers still fit: ESG buyers, painful power, large roofs. They will ask who gets paid Tk 10.50. Answer must be precise.",
    opportunity:
      "A 5.5-month installation window creates scarcity. Standard blocks, certified SKUs, and a clean legal structure are the capture mechanism.",
    threat:
      "Selling a PPA that silently assumes incentive capture; battery safety/quality under schedule pressure; DISCOM payment lag; duty/refinance still unresolved.",
    calls: [
      { initiative: "Battery-backed C&I rooftop as default product", call: "scale", why: "The incentive and standards now make BESS the eligibility path, and C&I BTM value was already the core." },
      { initiative: "Zero-CAPEX PPA / RESCO origination", call: "experiment", why: "Core model, but capture of Tk 10.50 is legally unverified. Run an owner-of-record variant in parallel." },
      { initiative: "RMG / export-factory focus", call: "scale", why: "Unchanged customer economics plus ESG pressure; roofs that can actually COD by Feb 2027 should be first." },
      { initiative: "Public-building / one-stop-service origination", call: "experiment", why: "Power Division one-stop language is real; public procurement cycles may miss the cutoff." },
      { initiative: "Balance-sheet light financing (IDCOL / green refinance / DFI)", call: "scale", why: "A 3-year kicker does not replace project finance. Capital stack is still the constraint." },
      { initiative: "Module-inverter-battery SKU standardisation to BSTI/SREDA", call: "scale", why: "Now a binary eligibility gate, not a QA preference." },
    ],
  },
};

export const SEED_ASSUMPTIONS: Assumption[] = [
  {
    id: "asm-surplus-tariff",
    category: "tariff",
    label: "Incentive surplus tariff (battery-backed RTS)",
    value: "10.50",
    unit: "Tk/kWh",
    previousValue: "n/a",
    originalFigure: "Tk 10.50 per unit",
    confidence: "high",
    needsReview: true,
    reviewReason: "New canonical export credit. Re-test PPA and IRR scenarios. Do not use as life-of-project tariff.",
    sourceNote: "Power Division circular as reported by Daily Star, TBS, Reuters — 1–2 Sep 2026",
    sortOrder: 1,
    updatedAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "asm-cost-cap",
    category: "tariff",
    label: "Stated generation-cost cap (with batteries)",
    value: "8.00",
    unit: "Tk/kWh",
    previousValue: null,
    originalFigure: "Tk 8 per unit",
    confidence: "high",
    needsReview: true,
    reviewReason: "Government benchmark, not Netso's actual LCOE. Compare to live EPC quotes.",
    sourceNote: "TBS quoting Power Division circular",
    sortOrder: 2,
    updatedAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "asm-retail-avg",
    category: "tariff",
    label: "Reported average retail grid price",
    value: "10.40",
    unit: "Tk/kWh",
    previousValue: null,
    originalFigure: "Tk 10.40 per unit",
    confidence: "medium",
    needsReview: true,
    reviewReason: "Average retail ≠ C&I bill. Replace with BERC schedule + sample RMG bills.",
    sourceNote: "The Daily Star, 2 Sep 2026",
    sortOrder: 3,
    updatedAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "asm-install-cutoff",
    category: "regulation",
    label: "Installation cutoff for incentive",
    value: "2027-02-28",
    unit: "date",
    previousValue: null,
    originalFigure: "28 February 2027",
    confidence: "high",
    needsReview: true,
    reviewReason: "COD/interconnection definition unverified (install vs. commission vs. net-meter live).",
    sourceNote: "Daily Star, TBS, Reuters",
    sortOrder: 4,
    updatedAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "asm-kicker-end",
    category: "regulation",
    label: "Incentive payment window end",
    value: "2030-02-28",
    unit: "date",
    previousValue: null,
    originalFigure: "28 February 2030",
    confidence: "high",
    needsReview: false,
    reviewReason: null,
    sourceNote: "Daily Star, TBS, Reuters",
    sortOrder: 5,
    updatedAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "asm-battery-required",
    category: "technology",
    label: "Battery required for incentive eligibility",
    value: "yes",
    unit: null,
    previousValue: "optional for most C&I offers",
    originalFigure: "rooftop solar power systems with battery storage",
    confidence: "high",
    needsReview: true,
    reviewReason: "Default product mix must include BESS on incentive-track. CAPEX/kWh assumption now material.",
    sourceNote: "All major recaps",
    sortOrder: 6,
    updatedAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "asm-resco-eligible",
    category: "regulation",
    label: "RESCO / PPA / third-party ownership eligible",
    value: "UNVERIFIED",
    unit: null,
    previousValue: null,
    originalFigure: "Recaps say 'customers/consumers'",
    confidence: "low",
    needsReview: true,
    reviewReason: "TRIGGER MODEL REVIEW and legal review. Do not originate incentive-led PPAs on an assumption.",
    sourceNote: "Secondary reporting only — gazette not ingested",
    sortOrder: 7,
    updatedAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "asm-effective-date",
    category: "regulation",
    label: "Scheme effective date",
    value: "CONFLICT",
    unit: "date",
    previousValue: null,
    originalFigure: "1 Sep vs 2 Sep vs ~30 Aug 2026",
    confidence: "medium",
    needsReview: true,
    reviewReason: "Conflict alert. Read gazette come-into-force clause.",
    sourceNote: "Reuters / Daily Star / TBS disagreement",
    sortOrder: 8,
    updatedAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "asm-capex-kwp",
    category: "capex",
    label: "C&I rooftop solar CAPEX (working)",
    value: "PENDING LIVE QUOTE",
    unit: "USD/kWp",
    previousValue: null,
    originalFigure: null,
    confidence: "low",
    needsReview: true,
    reviewReason: "No canonical Netso figure in NEIA. Do not invent. Pull last three EPC quotes.",
    sourceNote: "Internal — empty on purpose",
    sortOrder: 9,
    updatedAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "asm-bess-kwh",
    category: "capex",
    label: "Commercial BESS CAPEX (working)",
    value: "PENDING LIVE QUOTE",
    unit: "USD/kWh",
    previousValue: null,
    originalFigure: null,
    confidence: "low",
    needsReview: true,
    reviewReason: "Battery is now on the critical path. Empty until procurement returns listed LFP quotes.",
    sourceNote: "Internal — empty on purpose",
    sortOrder: 10,
    updatedAt: "2026-09-03T00:00:00.000Z",
  },
  {
    id: "asm-fx",
    category: "macro",
    label: "USD/BDT used in conversions",
    value: "as published",
    unit: "BDT per USD",
    previousValue: null,
    originalFigure: "Reuters implied ~Tk 122 / USD from Tk 10.50 = USD 0.086",
    confidence: "medium",
    needsReview: false,
    reviewReason: null,
    sourceNote: "Never silently convert; show Original → Converted",
    sortOrder: 11,
    updatedAt: "2026-09-03T00:00:00.000Z",
  },
];

export const SEED_SIGNALS: Signal[] = [
  {
    id: "opp-cod-sprint",
    kind: "opportunity",
    title: "Installation-window origination sprint",
    description:
      "Systems installed by 28 February 2027 are the ones that can even be discussed for Tk 10.50. A standardised battery-backed C&I block plus DISCOM one-stop choreography is the capture mechanism.",
    potentialValue: "High — dated national window",
    probability: "High if execution is industrialised",
    timeSensitivity: "Extreme — cutoff 28 Feb 2027",
    executionDifficulty: "High (interconnection, batteries, crew)",
    strategicFit: "Directly on Netso's C&I rooftop mandate",
    rank: 1,
  },
  {
    id: "opp-owner-variant",
    kind: "opportunity",
    title: "Owner-of-record contract variant",
    description:
      "If the gazette pays the customer, Netso can still deploy zero-CAPEX by making the customer the net-metering account holder and structuring a services/lease around it. That is a product experiment, not a press release.",
    potentialValue: "Preserves PPA origination if RESCO is ineligible",
    probability: "Medium — legal unknown",
    timeSensitivity: "This month",
    executionDifficulty: "Medium-high (legal + sales retrain)",
    strategicFit: "Protects the zero-CAPEX motion",
    rank: 2,
  },
  {
    id: "opp-certified-bom",
    kind: "opportunity",
    title: "Certified SKU lock as a sales weapon",
    description:
      "Competitors who quote uncertified batteries will be ineligible. A published compliant BOM is both risk control and differentiation.",
    potentialValue: "Win rate + bankability",
    probability: "High",
    timeSensitivity: "This week",
    executionDifficulty: "Low-medium",
    strategicFit: "High",
    rank: 3,
  },
  {
    id: "thr-resco-gap",
    kind: "threat",
    title: "PPA/RESCO may not be the payee",
    description:
      "Press language is consumer-centric. If third-party ownership is out, Netso's core offer cannot claim the kicker without a restructure.",
    potentialValue: "Could strand incentive-led pipeline",
    probability: "Unknown — treat as material",
    timeSensitivity: "Immediate",
    executionDifficulty: "n/a",
    strategicFit: "Hits core model",
    rank: 1,
  },
  {
    id: "thr-overclaim",
    kind: "threat",
    title: "Misselling a 3-year credit as a perpetual tariff",
    description:
      "Tk 10.50 through Feb 2030 is not a 20-year offtake. Customer and lender trust dies if proposals collapse the layers.",
    potentialValue: "Reputational and legal",
    probability: "High if templates are not rewritten",
    timeSensitivity: "Immediate",
    executionDifficulty: "n/a",
    strategicFit: "Culture/process threat",
    rank: 2,
  },
  {
    id: "thr-disco-lag",
    kind: "threat",
    title: "DISCOM-administered settlement lag",
    description:
      "Incentive cash sits with distribution utilities. No SLA in the recaps. Model haircuts required.",
    potentialValue: "NPV leakage on the kicker",
    probability: "Medium-high historically",
    timeSensitivity: "Before first COD",
    executionDifficulty: "n/a",
    strategicFit: "Finance",
    rank: 3,
  },
  {
    id: "thr-bess-quality",
    kind: "threat",
    title: "Battery quality under schedule pressure",
    description:
      "A six-month COD race on BESS in a cyclone/heat/corrosion environment is a safety and warranty event waiting to happen if procurement chases any listed cell.",
    potentialValue: "Site failure, claims, incentive claw-back risk (unverified)",
    probability: "Material if rushed",
    timeSensitivity: "Procurement cycle",
    executionDifficulty: "n/a",
    strategicFit: "Technology/ops",
    rank: 4,
  },
];
